dataset:
    path: /home/mjamali/proj/B/data
    num_frames: 65
    credentials_path: /home/mjamali/proj/B/data/credentials.yml
    remove_donloaded_video : True
    save_dir : /home/mjamali/proj/B/data/flowing_Tensors
    Multiprocessing_num_cores : 39
    size : [224,224]
    
    filter:
        limit :
            flag: True
            min: 0
            max: 20000
            
        tier1 : 
            - True
            # - False
        project_id :
            - A
            - C
            - D
            - E
            - F
            - G
            - H
            - I
            - J         
            - K
            - L               
            - M
        stalled:
            - 0
            #- 1
            
        # num_frames: # depth limit
         # - 0 # Min
         # - 40 # Max

        crowd_score: # depth limit
         - 0.0 # Min
         - 0.0 # Max    
