
train:
    resultDirectoryName : result
    experimentFolder : dir1
    experimentName: exp1_lr0001
    
    trainBatchSize : 16
    valBatchSize : 16
    num_Workers : 35
    startEpoch : 0
    endEpoch :   150
    lr:
        init: 0.0001
        lr_decay :  0.8
        lr_decay_epoch : 10
    device : cuda:1
        
options:
    logger:
        flag: True
    
model:
    load:
        flag: False
        path: "./"
    

dataset:
    path: /home/mjamali/proj/B/data
    num_frames: 65
    credentials_path: /home/mjamali/proj/B/data/credentials.yml
    remove_donloaded_video : True
    save_dir : /home/mjamali/proj/B/data/flowing_Tensors
    Multiprocessing_num_cores : 7
    
    K: 10 # ten-fold train-val
    
    filter:
        limit :
            flag: False
            min: 0
            max: 100
            
        tier1 : 
            - True
            - False
        project_id :
            - A
            - C
            - D
            - E
            - F
            - G
            - H
            - I
            - J        
            - K  
            - L               
            - M
        stalled:
            - 0
            #- 1
            
        # num_frames: # depth limit
         # - 0 # Min
         # - 40 # Max

        crowd_score: # depth limit
         - 0.0 # Min
         - 0.0 # Max    
