
train:
    resultDirectoryName : result
    experimentFolder : dir1
    experimentName: exp1
    
    trainBatchSize : 1
    valBatchSize : 1
    num_Workers : 0
    startEpoch : 0
    endEpoch :   50
    lr:
        init: 0.00001
        lr_decay :  0.5
        lr_decay_epoch : 10
        
options:
    logger:
        flag: True
    
model:
    load:
        flag: False
        path: "./"
    

dataset:
    path: ..\..\data
    num_frames: 65
    credentials_path: ..\..\data\credentials.yml
    remove_donloaded_video : True
    save_dir : ..\..\data\generated_Tensors
    Multiprocessing_num_cores : 4
    
    K: 10 # ten-fold train-val
    
    filter:
        limit :
            flag: False
            min: 0
            max: 100
            
        tier1 : 
            - True
            - False
        project_id :
            - A
            - C
            - D
            - E
            - F
            - G
            - H
            - I
            - J         
            - K               
            - M
        stalled:
            - 0
            #- 1
            
        # num_frames: # depth limit
         # - 0 # Min
         # - 40 # Max

        crowd_score: # depth limit
         - 0.0 # Min
         - 0.0 # Max    